language: ruby
rvm:
  - 2.4.1
  - 2.3.3
  - 2.2.6
  - 2.2.2
script: bundle exec rake
notifications:
  email: false
  irc:
    on_success: change
    on_failure: always
    channels:
    - irc.freenode.org#rubyonadhd
